name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Teste Padrão
      id: teste-padrao
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Teste Padrão
        setup-command: "./setup.sh"
        command: "./run-all.sh"
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTE-PADRAO_RESULTS: "${{steps.teste-padrao.outputs.result}}"
      with:
        runners: teste-padrao
